### ISSUE TITLE
This project is very good,But I have some questions

### ISSUE THREAD

**Issue by lemsn** [dealfonso/sapp#2]
This is a great project. Thank you for your contribution
But I found this problem when I used it:
The signature is successful, and I can see the picture of my signature in the browser. But when I opened the PDF with Adobe Acrobat, I found only the signature, not the image.

What should I do?

Thanks.

**Comment by dealfonso** [comment]
Hi,

the latest version had a bug when retrieving pagesize. I have just corrected it. Please test it and tell us how is it doing.

**Comment by lemsn** [comment]
Thank you.
Problems Persist:
 The signature is successful, and I can see the picture of my signature in the browser. 
But when I opened the PDF with Adobe Acrobat,  not the image.

**Comment by lemsn** [comment]
Now there is another problem:
When I opened it in the browser, I could see the image, but it had been rotated 90 degrees to the left

**Comment by dealfonso** [comment]
Sorry but I cannot reproduce the error... could you please provide an example?

**Comment by lemsn** [comment]
ok, I have understood the problem
1. Some documents have problems with invisible signatures. (eg: When I used the TCPDI signature and then use SAPP signature, I had a problem with the image not being visible).  

2.  When I opened it in the browser, I could see the image, but it had been rotated 90 degrees to the left  When I opened it in the browser, I could see the image, but it had been rotated 90 degrees to the left

![图片](https://user-images.githubusercontent.com/9290824/127463027-775e7234-a7f5-4789-bac6-f68fc79c22fd.png)

![图片](https://user-images.githubusercontent.com/9290824/127463212-b1b434fb-4b65-4966-bd82-6143b21fcdca.png)

![图片](https://user-images.githubusercontent.com/9290824/127463808-cfe47ec9-bd50-4ce0-ae12-c599a7579112.png)

**Comment by dealfonso** [comment]
Does your original signature certify de document? or allows further modifications?

Could you please send an example of a not signed document, the document signed once and the document signed twice?

**Comment by lemsn** [comment]
sorry . I have another question:
How can I put the signature image in a custom location, just like I did with TCPDI, and the image does not distort?
thank you very much.

**Comment by dealfonso** [comment]
Have you tested the example `pdfsigni.php`?. I think that it does what you are asking for.

**Comment by lemsn** [comment]
> 
> 
> Have you tested the example `pdfsigni.php`?. I think that it does what you are asking for.

I'm not using a command line  test, 

![图片](https://user-images.githubusercontent.com/9290824/127466631-5ebcd3cc-7b65-4d56-94df-348247f3b308.png)

**Comment by lemsn** [comment]
> 
> 
> Does your original signature certify de document? or allows further modifications?
> 
> Could you please send an example of a not signed document, the document signed once and the document signed twice?

The picture one  is  an example of a not signed document,   It was signed twice.



![图片](https://user-images.githubusercontent.com/9290824/127467496-c6cf6011-d8d8-40cd-aaaa-374bf9d3372a.png)

**Comment by dealfonso** [comment]
Sorry, but I mean the pdf files... otherwise I cannot reproduce the error.

**Comment by lemsn** [comment]
ok.
What is your email address?
 that I can send to you by email

**Comment by dealfonso** [comment]
for the sake of the open source, I'd prefer if you put the files in a public repository (e.g. here, you can drag and drop the files).

**Comment by dealfonso** [comment]
> ok.
> What is your email address?
> that I can send to you by email

have you managed to solve the problem? otherwise, could you please attach a PDF with an error?
